### PR TITLE
remove bits about symbol-indexed attr hashes

### PR DESCRIPTION
**Pull request by kmshultz**

### CODE REVIEW

**Comment by RSTJNII** [comment]
I think we should call out that we're preferring strings now,  Otherwise +1

**Comment by kmshultz** [comment]
I suppose I felt strings are implied, but it's good to be clear. This brings up another issue, though: do we want to axe dot notation (node.lsb.platform) wherever it makes sense? If so, we should make a note about that in place of the one I delete (e.g. "always index attr hashes with strings. avoid dot notation and symbols")

**Comment by RSTJNII** [comment]
I'm not familiar with dot notation, but I don't like the looks of it.

**Comment by thomascate** [comment]
I think the dot notation is only used when you're getting things out of the ruby environment not the chef environment.

For example node.chef_environment and node.lsb.platform will work, however' node['chef_environment'] and node['lsb']['platform'] don't exist.

**Pull request merged**
