### PR TITLE
Further Rubocop check tuning

### PR DESCRIPTION
**Pull request by RSTJNII**
Further tuning of Rubocop for style recommendations I think are anti-patterns or that are going to cause more problems then they fix.

### CODE REVIEW

**Comment by thomascate** [comment]
+1
Maybe even bump method length to 40?

**Comment by kmshultz** [comment]
I'm good with this. Especially line length and  RedundantReturn Enabled: false.

**Comment by RSTJNII** [comment]
We can bump line length up to 40 if others want.  I'm indifferent to that change, but I think it should definitely fail with line lengths over 50.

I pulled these max length numbers out of the air so debate on them is welcomed.

**Comment by prometheanfire** [comment]
method lengths up to 40 would would be good, given that they will all have a nine character word in it (10 with the underscore)

**Comment by thomascate** [comment]
I'm pretty sure methodlength is number of lines in the method itself, not number of characters in a line.

**Comment by RSTJNII** [comment]
> I'm pretty sure methodlength is number of lines in the method itself, not number of characters in a line.

That's correct

**Pull request merged**
